Change package name
Cray-HPE/pit-nexus pull request #1
Opened 2021-11-30 15:52 UTC by rustydb

Change name to match repo name.

2021-11-30 15:54 UTC, zcrisler requested changes
Need to change the name of the spec file to `pit-nexus.spec` and update the version to 1.1.0.

2021-11-30 20:58 UTC, rustydb commented
Smoke testing worked.
Double-checking docs-csm 1.2 and main first before calling this okay.

2021-12-01 14:38 UTC, rustydb commented
> Need to change the name of the spec file to `pit-nexus.spec` and update the version to 1.1.0.

Seems okay doc-wise:
```
[602]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/docs-csm> grep -Ri cray-nexus *
install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml:30:          3.  Load the skopeo image installed by the cray-nexus RPM
install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml:38:          podman load -i /var/lib/cray/container-images/cray-nexus/skopeo-stable.tar quay.io/skopeo/stable
operations/package_repository_management/Nexus_Deployment.md:3:Nexus is deployed with the `cray-nexus` chart to the `nexus` namespace as part of the Cray System Management \(CSM\) release. Nexus is deployed after critical platform services are up and running. Product installers configure and populate Nexus blob stores and repositories using the `cray-nexus-setup` container image. As a result, there is no singular product that provides all Nexus repositories or assets; instead, individual products must be installed. However, CSM configures the `charts` Helm repository and the `registry` Docker repository, which all products may use.
operations/package_repository_management/Nexus_Deployment.md:7:For a complete set of available settings, consult the values.yaml file for the `cray-nexus` chart. The most common customizations to set are specified in the following table. They must be set in the customizations.yaml file under the `spec.kubernetes.services.cray-nexus` setting.
operations/package_repository_management/Nexus_Deployment.md:13:|`sonatype-nexus.persistence.storageSize`|`1000Gi`|Nexus storage size, may be increased after installation; critical if `spec.kubernetes.services.cray-nexus-setup.s3.enabled` is `false`|
operations/package_repository_management/Nexus_Deployment.md:45:**Warning:** The `cray-nexus` chart deploys Nexus with a single replica and the corresponding `nexus-data` PVC with `RWX` access mode. Nexus should **NEVER** be scaled to more than one replica; otherwise, the instance data in `nexus-data` PV will most likely be corrupted. Using `RWX` access mode enables Nexus to quickly restart on another worker node in the event of a node failure and avoid additional delay because of volume multi-attach errors.
operations/package_repository_management/Nexus_Deployment.md:55:Product installers vendor the `dtr.dev.cray.com/cray/cray-nexus-setup:0.4.0` container image, which includes helper scripts for working with the Nexus REST API to update and modify repositories. Product release distributions will include the nexus-blobstores.yaml and nexus-repositories.yaml files, which define the Nexus blob stores and repositories required for that version of the product. Also, expect to find directories that include specific types of assets:
operations/package_repository_management/Troubleshoot_Nexus.md:80:successful. If `helm status -n nexus cray-nexus` indicates the status is
operations/package_repository_management/Manage_Repositories_with_Nexus.md:291:Installers typically define Nexus repositories in nexus-repositories.yaml and rely on the `nexus-repositories-create` helper script included in the cray/cray-nexus-setup container image to facilitate creation.
operations/package_repository_management/Manage_Repositories_with_Nexus.md:372:Installers typically define Nexus blob stores in `nexus-blobstores.yaml` and rely on the `nexus-blobstores-create` helper script included in the cray/cray-nexus-setup container image to facilitate creation.
operations/utility_storage/Restore_Corrupt_Nexus.md:35:      /mnt/pitdata/csm-0.9.4/helm/cray-nexus-0.6.0.tgz <-- this is the helm chart to use
operations/utility_storage/Restore_Corrupt_Nexus.md:50:   ncn-m001# helm uninstall -n nexus cray-nexus
operations/utility_storage/Restore_Corrupt_Nexus.md:59:1. Re-install the `cray-nexus` helm chart (using the chart and manifest determined in step 1).
operations/utility_storage/Restore_Corrupt_Nexus.md:62:   ncn-m001# loftsman ship --manifest-path /mnt/pitdata/csm-0.9.4/manifests/nexus.yaml --charts-path /mnt/pitdata/csm-0.9.4/helm/cray-nexus-0.6.0.tgz
operations/image_management/Build_an_Image_Using_IMS_REST_Service.md:12:    -   `cray-nexus`, the Nexus repository manager service
operations/image_management/Delete_or_Recover_Deleted_IMS_Content.md:58:    -   `cray-nexus`, the Nexus repository manager service
operations/image_management/Delete_or_Recover_Deleted_IMS_Content.md:159:    -   `cray-nexus`, the Nexus repository manager service
operations/image_management/Customize_an_Image_Root_Using_IMS.md:14:    - `cray-nexus`, the Nexus repository manager service
upgrade/1.2/scripts/upgrade/update-customizations.sh:120:yq w -i --style=single "$c" 'spec.proxiedWebAppExternalHostnames.customerManagement[+]' "{{ kubernetes.services['cray-nexus'].istio.ingress.hosts.ui.authority }}"
upgrade/1.2/scripts/upgrade/update-customizations.sh:135:yq w -i "$c" 'spec.kubernetes.services.cray-nexus.istio.ingress.hosts.ui.authority' 'nexus.cmn.{{ network.dns.external }}'
upgrade/1.2/scripts/upgrade/prerequisites.sh:347:    pdsh -b -S -w $(grep -oP 'ncn-w\w\d+' /etc/hosts | sort -u |  tr -t '\n' ',') 'for image in sonatype/nexus3:3.25.0 dtr.dev.cray.com/cray/proxyv2:1.6.13-cray1 dtr.dev.cray.com/baseos/busybox:1 docker.io/sonatype/nexus3:3.25.0 dtr.dev.cray.com/cray/cray-nexus-setup:0.3.2; do crictl pull $image; done'
[603]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/docs-csm> grep -Ri cray-nexus * | grep rpm
[604]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/docs-csm> grep -Ri cray-nexus * | grep zypper
[605]rusty@C02F43JEMD6P:~/gitstuffs/cray-shasta/docs-csm>
```

2021-12-01 15:41 UTC, zcrisler approved these changes

2021-12-01 15:58 UTC, merged